// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAmH3aU53WqjEBELHlwP6DhvRpOzNkW4',
    appId: '1:629588711047:web:6714a6d7a52ab6c0b58a22',
    messagingSenderId: '629588711047',
    projectId: 'chatbot-408914',
    authDomain: 'chatbot-408914.firebaseapp.com',
    storageBucket: 'chatbot-408914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVToextBmc8ztJ8oBT0SxVfTK4kDJMBg',
    appId: '1:629588711047:android:ed5b64e7e6e58152b58a22',
    messagingSenderId: '629588711047',
    projectId: 'chatbot-408914',
    storageBucket: 'chatbot-408914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMNNxOhEZYXSAIgq-1nClGVmFTpGC04_U',
    appId: '1:629588711047:ios:111c78db18428e3db58a22',
    messagingSenderId: '629588711047',
    projectId: 'chatbot-408914',
    storageBucket: 'chatbot-408914.appspot.com',
    iosBundleId: 'com.example.aiChatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMNNxOhEZYXSAIgq-1nClGVmFTpGC04_U',
    appId: '1:629588711047:ios:4620c8755de451a2b58a22',
    messagingSenderId: '629588711047',
    projectId: 'chatbot-408914',
    storageBucket: 'chatbot-408914.appspot.com',
    iosBundleId: 'com.example.aiChatBot.RunnerTests',
  );
}
